name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    strategy:
      matrix:
        swift-version: ['5.9']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Resolve dependencies
      run: swift package resolve
    
    - name: Build package
      run: swift build
    
    - name: Run tests (excluding UI tests)
      run: swift test --filter AppAboutViewTests